In [1]:
import pandas as pd
import geopandas as gpd
from ipyleaflet import Map, GeoData, LayersControl, basemaps, basemap_to_tiles

In [2]:
df = pd.read_csv(r"data\statsnz-2023-census-main-means-of-travel-to-work-by-statistical-area-CSV\2023-census-main-means-of-travel-to-work-by-statistical-area.csv")

df

,SA22023_V1_00_usual_residence_address,SA22023_V1_00_NAME_usual_residence_address,SA22023_V1_00_NAME_ASCII_usual_residence_address,SA22023_V1_00_workplace_address,SA22023_V1_00_NAME_workplace_address,SA22023_V1_00_NAME_ASCII_workplace_address,2018_Work_at_home,2018_Drive_a_private_car_truck_or_van,2018_Drive_a_company_car_truck_or_van,2018_Passenger_in_a_car_truck_van_or_company_bus,...,2023_Drive_a_private_car_truck_or_van,2023_Drive_a_company_car_truck_or_van,2023_Passenger_in_a_car_truck_van_or_company_bus,2023_Public_bus,2023_Train,2023_Bicycle,2023_Walk_or_jog,2023_Ferry,2023_Other,2023_Total_stated
0,100100,North Cape,North Cape,100100,North Cape,North Cape,144,117,33,9,...,165,39,12,-999,-999,-999,15,-999,6,438
1,100100,North Cape,North Cape,100200,Rangaunu Harbour,Rangaunu Harbour,-999,30,9,-999,...,42,6,-999,-999,-999,-999,-999,-999,-999,51
2,100100,North Cape,North Cape,100500,Tangonge,Tangonge,-999,-999,-999,-999,...,-999,6,-999,-999,-999,-999,-999,-999,-999,9
3,100100,North Cape,North Cape,100700,Kaitāia East,Kaitaia East,-999,51,15,-999,...,66,21,-999,-999,-999,-999,-999,-999,-999,93
4,100100,North Cape,North Cape,100800,Kaitāia West,Kaitaia West,-999,24,-999,-999,...,27,-999,-999,-999,-999,-999,-999,-999,-999,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65051,363301,Bluff,Bluff,362501,Strathern,Strathern,-999,-999,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,6
65052,363301,Bluff,Bluff,362601,Heidelberg,Heidelberg,-999,-999,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
65053,363301,Bluff,Bluff,363001,Clifton-Kew,Clifton-Kew,-999,9,-999,-999,...,21,-999,-999,-999,-999,-999,-999,-999,-999,21
65054,363301,Bluff,Bluff,363100,Woodend-Greenhills,Woodend-Greenhills,-999,33,-999,-999,...,27,-999,-999,-999,-999,-999,-999,-999,-999,30
65055,363301,Bluff,Bluff,363301,Bluff,Bluff,84,258,39,21,...,261,33,24,-999,-999,-999,30,-999,6,429

In [3]:
df = df.replace(-999,0)

In [4]:
list(df["SA22023_V1_00_NAME_ASCII_usual_residence_address"].unique())

['North Cape',
 'Rangaunu Harbour',
 'Karikari Peninsula',
 'Tangonge',
 'Ahipara',
 'Kaitaia East',
 'Kaitaia West',
 'Rangitihi',
 'Oruru-Parapara',
 'Doubtless Bay',
 'Herekino-Takahue',
 'Peria',
 'Taemaro-Oruaiti',
 'Whakapaku',
 'Hokianga North',
 'Kohukohu-Broadwood',
 'Whakarara',
 'Kaeo',
 'Omahuta Forest-Horeke',
 'Hokianga South',
 'Lake Manuwai-Kapiro',
 'Okaihau',
 'Waitoki',
 'Rangitane-Purerua',
 'Waipapa',
 'Puketotara',
 'Hikuai',
 'Waima Forest',
 'Riverview',
 'Waipoua Forest',
 'Kerikeri Central',
 'Kerikeri South',
 'Ohaeawai-Waimate North',
 'Puketona-Waitangi',
 'Ngapuhi',
 'Kaikohe',
 'Pakaraka',
 'Haruru',
 'Russell',
 'Paihia',
 'Mataraua Forest',
 'Matawaia-Taumarere',
 'Russell Peninsula',
 'Opua (Far North District)',
 'Russell Forest-Rawhiti',
 'Moerewa',
 'Kawakawa',
 'Maromaku',
 'Mangakahia-Hukerenui',
 'Whangaruru',
 'Matarau',
 'Hikurangi',
 'Kauri',
 'Maungatapere',
 'Kamo West',
 'Matapouri-Tutukaka',
 'Kiripaka',
 'Kamo East',
 'Granfield Reserve',
 'Kamo Central',
 'Waihi Rural',
 'Whau Valley',
 'Tikipunga North',
 'Te Poi',
 'Pukenui',
 'Otangarei',
 'Tikipunga South',
 'Maeroa',
 'Kensington (Whangarei District)',
 'Abbey Caves-Glenbervie',
 'Riverlea',
 'Mairtown',
 'Maunu',
 'Horahora',
 'Woodhill-Vinetown',
 'Whangarei Central',
 'Riverside',
 'Raumanga',
 'Tarewa',
 'Morningside (Whangarei District)',
 'Ngunguru',
 'Otaika-Portland',
 'Oakleigh-Mangapai',
 'Port-Limeburners',
 'Pataua',
 'Onerahi Park',
 'Sherwood Rise',
 'Onerahi',
 'Parua Bay',
 'Bream Bay',
 'One Tree Point',
 'Ruakaka',
 'Bream Head',
 'Waipu',
 'Waipu Rural',
 'Kaipara Coastal',
 'Maungaru',
 'Dargaville',
 'Ruawai-Matakohe',
 'Otamatea (Kaipara District)',
 'Maungaturoto',
 'Kaiwaka',
 'Mangawhai Rural',
 'Mangawhai Heads',
 'Mangawhai',
 'Okahukura Peninsula',
 'Cape Rodney',
 'Karapiro',
 'Wellsford',
 'South Head',
 'Kaipara Hills',
 'Dome Valley-Matakana',
 'Mapara',
 'Warkworth West',
 'Puhoi Valley',
 'Warkworth East',
 'Sandspit',
 'Tawharanui Peninsula',
 'Kaukapakapa',
 'Kaukapakapa Rural',
 'Snells Beach',
 'Barrier Islands',
 'Mahurangi Peninsula',
 'Wainui-Waiwera',
 'Poike',
 'Ara Hill',
 'Parakai',
 'Helensville Rural',
 'Helensville',
 'Waikoukou Valley',
 'Orewa North',
 'Orewa West',
 'Hatfields Beach',
 'Orewa South',
 'Millwater North',
 'Orewa Central',
 'Millwater Central',
 'Waipatukahu',
 'Millwater South',
 'Milldale',
 'Dairy Flat North',
 'Dairy Flat West',
 'Kingsway',
 'Silverdale Central (Auckland)',
 'Red Beach West',
 'Red Beach East',
 'Silverdale South (Auckland)',
 'Stillwater',
 'Waimauku',
 'Gulf Islands',
 'Vipond',
 'Muriwai',
 'Stanmore Bay West',
 'Kumeu Rural West',
 'Okura Bush',
 'Whangaparaoa Central',
 'Wade Heads-Arkles Bay',
 'Kumeu-Huapai North',
 'Kumeu-Huapai South',
 'Stanmore Bay East',
 'Manly West',
 'Kawaha',
 'Muriwai Valley-Bethells Beach',
 'Tindalls-Matakatia',
 'Koutu',
 'Coatesville',
 'Dairy Flat South',
 'Ohope',
 'Gulf Harbour North',
 'Poukawa',
 'Manly East',
 'Clive',
 'Riverhead',
 'Lucknow',
 'Army Bay',
 'Kumeu Rural East',
 'Gulf Harbour South',
 'Paremoremo West',
 'Taupaki',
 'Long Bay',
 'Paremoremo East',
 'Albany Heights',
 'Awaruku',
 'Fairview Heights',
 'Iona',
 'Whenuapai',
 'Whenuapai West',
 'Massey Red Hills',
 'Waitakere Ranges North',
 'Torbay West',
 'Oakura',
 'Torbay East',
 'Kaitake',
 'Albany Central',
 'Westown',
 'Albany West',
 'Glamorgan',
 'Oteha East',
 'Northcross',
 'Oteha West',
 'Waiake',
 'Waitakere',
 'Albany South',
 'Browns Bay South West',
 'Browns Bay Central',
 'Schnapper Rock',
 'Pinehill North',
 'Pinehill South',
 'North Harbour',
 'Browns Bay South East',
 'Ohangai',
 'Greenhithe West',
 'Sandon',
 'Rothesay Bay',
 'Greenhithe East',
 'Hobsonville',
 'Inlet Waitemata Harbour',
 'Greenhithe South',
 'Murrays Bay West',
 'Westgate South',
 'Windsor Park',
 'West Harbour West',
 'Unsworth Heights West',
 'Murrays Bay East',
 'Birdwood West',
 'Hobsonville Point Catalina Bay',
 'Hobsonville Point Park',
 'Newbury',
 'Mairangi Bay South',
 'Hobsonville Scott Point',
 'West Harbour Clearwater Cove',
 'Massey Royal Road West',
 'Unsworth Heights East',
 'Mairangi Bay North',
 'Waiopehu',
 'Massey Central',
 'West Harbour Luckens Point',
 'Swanson Rural',
 'Bayview East (Auckland)',
 'Waitohu',
 'Sunnynook South',
 'Sunnynook North',
 'Bayview West (Auckland)',
 'Totara Vale North',
 'Royal Heights North',
 'Papakowhai',
 'Massey West',
 'Whitby',
 'Beach Haven West',
 'Totara Vale South',
 'Swanson',
 'Woodend',
 'Bayview South (Auckland)',
 'Campbells Bay',
 'Royal Heights South',
 'Beach Haven East',
 'Massey Keegan',
 'Forrest Hill North',
 'Glenfield North',
 'Birkdale North',
 'Birkdale Central',
 'Styx',
 'Massey South',
 'Islington',
 'Ranui North',
 'Eiffelton',
 'Glenfield West',
 'Te Atatu Peninsula North West',
 'Forrest Hill West',
 'Glenfield South West',
 'Wairau Valley',
 'Forrest Hill East',
 'Castor Bay North',
 'Hadlow',
 'Castor Bay South',
 'Ranui Domain',
 'Beach Haven South',
 'Glenfield Central',
 'Piha',
 'Ranui South West',
 'Henderson Larnoch',
 'Birkdale South',
 'Te Atatu Peninsula Central',
 'Glenfield East',
 'Glenwood',
 'Henderson Valley',
 'Twizel',
 'Te Atatu Peninsula West',
 'Henderson Lincoln West',
 'Maheno',
 'Ranui South East',
 'Henderson Lincoln East',
 'Birkenhead West',
 'Birkenhead North West',
 'Te Atatu Peninsula East',
 'Cardrona',
 'Milford West',
 'Westlake',
 'Hillcrest North (Auckland)',
 'Henderson Lincoln South',
 'Hillcrest West (Auckland)',
 'Milford Central',
 'Summerland South',
 'Summerland North',
 'Hillcrest East (Auckland)',
 'Wakari',
 'Chatswood',
 'Te Atatu South-Edmonton',
 'Birkenhead North',
 'Takapuna West',
 'Henderson North',
 'Henderson West',
 'Takapuna Central',
 'Western Heights (Auckland)',
 'Birkenhead South',
 'Waiatarua',
 'Te Atatu South-North',
 'Te Atatu South-Central',
 'Northcote Central (Auckland)',
 'Riverton',
 'Akoranga',
 'Northcote South (Auckland)',
 'Strathern',
 'Henderson Central',
 'Te Atatu South-McLeod North',
 'Henderson Valley Park',
 'Henderson North East',
 'Waitakere Ranges South',
 'Northcote Tuff Crater',
 'Northcote Point (Auckland)',
 'McLaren Memorial Park',
 'Henderson East',
 'Te Atatu South-McLeod South',
 'Takapuna South',
 'Rosebank Peninsula',
 'Hauraki',
 'Glendene North West',
 'Glendene North East',
 'Sunnyvale West-Parrs Park',
 'Sunnyvale East',
 'Point Chevalier West',
 'Belmont (Auckland)',
 'Bayswater',
 'Glendene South',
 'Glen Eden West',
 'Herne Bay',
 'Westmere North',
 'Point Chevalier North',
 'Point Chevalier East',
 'Oratia',
 'Glen Eden Rosier',
 'Saint Marys Bay',
 'Westmere South-Western Springs',
 'Ponsonby West',
 'Kelston North',
 'Avondale Rosebank (Auckland)',
 'Narrow Neck',
 'Glen Eden North',
 'Glen Eden Woodglen',
 'Glen Eden Konini',
 'Kelston South',
 'Waterview',
 'Ponsonby East',
 'Wynyard-Viaduct',
 'Stanley Point',
 'Glen Eden Central',
 'Grey Lynn North',
 'Freemans Bay',
 'Avondale West (Auckland)',
 'College Hill',
 'Mount Albert West',
 'Avondale North West (Auckland)',
 'Avondale North East (Auckland)',
 'Grey Lynn West',
 'Mount Albert North',
 'New Lynn North',
 'Victoria Park',
 'Konini Road',
 'New Lynn North West',
 'Hobson Ridge North',
 'Grey Lynn Central',
 'Fruitvale',
 'Devonport',
 'Avondale Central (Auckland)',
 'Queen Street',
 'Quay Street-Customs Street',
 'Hobson Ridge Central',
 'Grey Lynn East',
 'Morningside (Auckland)',
 'Shortland Street',
 'Hobson Ridge South',
 'New Lynn Central',
 'Cheltenham',
 'Queen Street South West',
 'Mount Albert Central',
 'Karangahape West',
 'Karangahape East',
 'Kingsland',
 'Anzac Avenue',
 'Waima-Woodlands Park',
 'Kaurilands',
 'Auckland-University',
 'New Lynn Seabrook',
 'Avondale South (Auckland)',
 'Symonds Street North West',
 'Mount Albert South',
 'Symonds Street West',
 'Titirangi East',
 'Owairaka West',
 'New Lynn Central South',
 'The Strand',
 'St Lukes',
 'Symonds Street East',
 'Eden Terrace',
 'Grafton West',
 'Grafton',
 'Eden Park',
 'Sandringham North',
 'Parnell West',
 'New Lynn South',
 'New Lynn South East',
 'New Windsor North',
 'Titirangi South',
 'Owairaka East',
 'Eden Valley',
 'Sandringham Central',
 'Glenavon',
 'Blockhouse Bay North',
 'Blockhouse Bay Central',
 'Green Bay North',
 'Parnell East',
 'Laingholm',
 'Sandringham West',
 'Mount Eden North East',
 'Mount Eden North',
 'Wesley West',
 'Green Bay South',
 'Balmoral',
 'Sandringham East',
 'New Windsor South',
 'New Windsor East',
 'Mount Eden West',
 'Newmarket',
 'Newmarket Park',
 'Blockhouse Bay North East',
 'Epsom North',
 'Wesley South',
 'Blockhouse Bay South',
 'Mount Eden East',
 'Wesley East',
 'Orakei West',
 'Maungawhau',
 'Remuera West',
 'Blockhouse Bay East',
 'Mount Roskill West',
 'Mount Roskill North',
 'Mount Roskill White Swan',
 'Mount Roskill Nirvana',
 'Mount Eden South',
 'Remuera Waitaramoa',
 'Orakei East',
 'Epsom Central-North',
 'Mount St John',
 'Mount Roskill Central North',
 'Remuera North',
 'Mount Roskill North East',
 'Mount Roskill Central South',
 'Epsom Central-South',
 'Lynfield Central',
 'Lynfield Harbour View',
 'Remuera South',
 'Mission Bay',
 'Mission Bay Eastridge',
 'Three Kings North',
 'Mount Roskill South',
 'Epsom East',
 'Remuera Waiata',
 'Epsom South',
 'Kohimarama Bay',
 'Kohimarama Stadium',
 'Meadowbank West',
 'Three Kings South',
 'Hillsborough North (Auckland)',
 'Mount Roskill Central East',
 'Greenlane North',
 'Greenlane Central',
 'Mount Roskill South East',
 'Remuera East',
 'Waikowhai Bay',
 'Royal Oak West (Auckland)',
 'Saint Heliers West',
 'One Tree Hill Oranga',
 'One Tree Hill Amaru',
 'Hillsborough Central (Auckland)',
 'Saint Heliers North',
 'Remuera Abbotts Park',
 'Meadowbank East',
 'Ellerslie Central',
 'Royal Oak East (Auckland)',
 'Saint Heliers South',
 'Hillsborough South (Auckland)',
 'Saint Johns West',
 'Greenlane South',
 'Remuera Waiatarua',
 'Glendowie North',
 'Onehunga West',
 'Ellerslie West',
 'Onehunga North',
 'Ellerslie East',
 'Saint Johns East',
 'Oneroa West',
 'Glen Innes West',
 'Ellerslie South',
 'Stonefields West',
 'Onehunga Central',
 'Glendowie South West',
 'Glendowie South East',
 'Oranga',
 'Te Papapa',
 'Mount Wellington North West',
 'Panmure Glen Innes Industrial',
 'Onehunga-Te Papapa Industrial',
 'Stonefields East',
 'Glen Innes East-Wai O Taiki Bay',
 'Penrose',
 'Mount Wellington North East',
 'Mangere Bridge Ambury',
 'Mount Wellington Ferndale',
 'Mangere Bridge',
 'Point England North',
 'Point England South',
 'Bucklands Beach North',
 'Mount Wellington East',
 'Mount Wellington West',
 'Panmure West',
 'Oneroa East-Palm Beach',
 'Tamaki West',
 'Tamaki East',
 'Panmure East',
 'Mount Wellington Central',
 'Mount Wellington Hamlin',
 'Sylvia Park',
 'Mangere Mountain View',
 'Surfdale',
 'Mount Wellington Industrial',
 'Half Moon Bay West',
 'Auckland Airport',
 'Eastern Beach',
 'Sunnyhills West',
 'Favona North',
 'Pakuranga North',
 'Bucklands Beach Central',
 'Farm Cove',
 'Mangere North',
 'Favona West',
 'Ostend',
 'Half Moon Bay North East',
 'Mangere West',
 'Pakuranga West',
 'Mount Wellington South West',
 'Sunnyhills East',
 'Half Moon Bay South East',
 'Favona East',
 'Mount Wellington South East',
 'Bucklands Beach Murvale',
 'Bucklands Beach South',
 'Pakuranga Central',
 'Awhitu',
 'Harania North',
 'Otahuhu Central',
 'Mangere Central',
 'Otahuhu North West',
 'Otahuhu North East',
 'Howick West',
 'Pakuranga Heights North West',
 'Sutton Park',
 'Mellons Bay',
 'Pakuranga Heights East',
 'Otahuhu East',
 'Mangere South',
 'Onetangi',
 'Harania South',
 'Highland Park (Auckland)',
 'Otahuhu South West',
 'Pakuranga Heights South West',
 'Mangere Mascot',
 'Waiheke East',
 'Massey Road West',
 'Otahuhu South',
 'Howick Central',
 'Massey Road North',
 'Botany Downs West',
 'East Tamaki',
 'Howick East',
 'Burswood',
 'Massey Road South',
 'Middlemore',
 'Mangere South East',
 'Botany Downs East',
 'Grange',
 'Golflands',
 'Aorere North',
 'Mangere East',
 'Cockle Bay',
 'Otara West',
 'Aorere Central',
 'Northpark North',
 'Somerville',
 'Northpark South',
 'Papatoetoe North',
 'Dingwall',
 'Aorere South West',
 'Otara Central',
 'Aorere South East',
 'Shelly Park',
 'Huntington Park',
 'Dannemora North-Shamrock Park',
 'Papatoetoe North West',
 'Papatoetoe West',
 'Papatoetoe Central West',
 'Papatoetoe Central East',
 'Sunkist Bay',
 'Redcastle',
 'Otara East',
 'Turanga',
 'Dannemora South',
 'Armoy',
 'Manukau Central',
 'Papatoetoe North East',
 'Papatoetoe East',
 'Otara South West',
 'Otara South',
 'Ferguson',
 'Papatoetoe South West',
 'Botany Junction',
 'Middlefield',
 'Papatoetoe South',
 'Point View',
 'Te Puru',
 'Puhinui North',
 'Savonna',
 'Puhinui South',
 'Rongomai West',
 'Baverstock',
 'Puhinui East',
 'Rongomai East',
 'Ormiston North',
 'Maraetai',
 'Chapel Downs',
 'Wiri West',
 'Clover Park North',
 'Clover Park East',
 'Mission Heights North',
 'Clover Park South',
 'Donegal Park West',
 'Donegal Park East',
 'Ormiston Central',
 'Ormiston South',
 'Mission Heights South',
 'Hilltop (Auckland)',
 'Wiri North',
 'Wiri East',
 'Goodwood Heights West',
 'Goodwood Heights East',
 'Ormiston East',
 'Bremner Ridge',
 'Ormiston South East',
 'Clendon Park North',
 'Burbank',
 'Totara Heights',
 'Tuscany Heights',
 'Homai East',
 'Homai West',
 'Homai Central',
 'The Gardens (Auckland)',
 'Clarks Beach',
 'Clendon Park West',
 'Hillpark North',
 'Clendon Park East',
 'Karaka Creek',
 'Rowandale West',
 'Rowandale East',
 'Manurewa Central',
 'Weymouth West',
 'Weymouth Central',
 'Hillpark South',
 'Alfriston',
 'Weymouth East',
 'Leabank',
 'Weymouth South',
 'Manurewa East',
 'Manurewa West',
 'Manurewa South',
 'Randwick Park East',
 'Wattle Downs West',
 'Wattle Downs North',
 'Randwick Park West',
 'Kingseat-Karaka',
 'Wattle Downs East',
 'Takanini North',
 'Takanini Industrial',
 'Conifer Grove West',
 'Conifer Grove East',
 'Takanini West',
 'Takanini South',
 'Takanini East',
 'Takanini Central',
 'Ardmore',
 'Glenbrook',
 'Hingaia',
 'Takanini South East',
 'Takanini McLennan',
 'Papakura West',
 'Kawakawa Bay-Orere',
 'Clevedon',
 'Papakura North',
 'Pahurehure',
 'Papakura Central',
 'Papakura North East',
 'Twin Parks Rise',
 'Karaka Lakes',
 'Papakura Kelvin',
 'Papakura Eastburn',
 'Papakura Massey Park',
 'Rosehill',
 'Patumahoe',
 'Patumahoe Rural',
 'Papakura East',
 'Harbour View Heights',
 'Opaheke',
 'Papakura Industrial',
 'Red Hill',
 'Drury West',
 'Drury East',
 'Tamakae',
 'Runciman',
 'Hamilton Estate',
 'Drury South Crossing',
 'Waihoehoe',
 'Waiuku Central',
 'Waiuku East',
 'Kendallvale',
 'Puni',
 'Ramarama',
 'Hunua',
 'Pukekohe North',
 'Pukekohe North West',
 'Anselmi Ridge',
 'Pukekohe West',
 'Pukekohe South West',
 'Cape Hill',
 'Rosa Birch Park',
 'Rooseville Park',
 'Cloverlea (Auckland)',
 'Pukekohe Central',
 'Pukekohe Hospital',
 'Buckland',
 'Bombay Hills',
 'Ararimu',
 'Colville',
 'Islands Thames-Coromandel District',
 'Coromandel',
 'Mercury Bay North',
 'Whitianga North',
 'Whitianga South',
 'Whitianga Waterways',
 'Thames Coast',
 'Cooks Beach-Ferry Landing',
 'Mercury Bay South',
 'Kauaeranga',
 'Thames North',
 'Thames Central',
 'Thames South',
 'Totora-Kopu',
 'Tairua',
 'Pauanui',
 'Matatoki-Puriri',
 'Whangamata Rural',
 'Whangamata West',
 'Whangamata East',
 'Miranda-Pukorokoro',
 'Hauraki Plains North',
 'Hauraki Plains East',
 'Ngatea',
 'Hauraki Plains South',
 'Paeroa Rural',
 'Paeroa',
 'Waihi North',
 'Waihi East',
 'Waihi South',
 'Aka Aka',
 'Mangatangi',
 'Tuakau Rural',
 'Tuakau North',
 'Onewhero',
 'Pokeno Rural',
 'Tuakau South',
 'Port Waikato-Waikaretu',
 'Pokeno North',
 'Pokeno South',
 'Pukekawa',
 'Maramarua',
 'Te Kauwhata West',
 'Whangamarino',
 'Te Akau',
 'Te Kauwhata East',
 'Huntly Rural',
 'Waerenga',
 'Huntly West',
 'Huntly East',
 'Huntly South',
 'Raglan',
 'Whitikahu',
 'Te Uku',
 'Whale Bay',
 'Taupiri-Lake Kainui',
 'Ngaruawahia North',
 'Ngaruawahia Central',
 'Ngaruawahia South',
 'Kainui-Gordonton',
 'Te Kowhai',
 'Whatawhata West',
 'Horotiu',
 'Horsham Downs',
 'Whatawhata East',
 'Rotokauri',
 'Hamilton Park',
 'Eureka-Tauwhare',
 'Tamahere North',
 'Tamahere West',
 'Pukemoremore',
 'Tamahere South',
 'Tahuna-Mangateparu',
 'Mangaiti',
 'Tatuanui',
 'Tahuroa',
 'Morrinsville North',
 'Morrinsville East',
 'Morrinsville West',
 'Te Aroha East',
 'Te Aroha West',
 'Waihou-Manawaru',
 'Waitoa-Ngarua',
 'Richmond Downs-Wardville',
 'Waharoa-Peria',
 'Okauia',
 'Hinuera',
 'Matamata North',
 'Matamata West',
 'Matamata East',
 'Te Rapa North',
 'Flagstaff North West',
 'Flagstaff North East',
 'Burbush-Baverstock',
 'Flagstaff South',
 'Rototuna North',
 'Pukete West',
 'Flagstaff East',
 'Rototuna West',
 'Rototuna East',
 'Pukete East',
 'Te Manatu',
 'Rototuna South West',
 'Rototuna South East',
 'Te Rapa South',
 'Saint Andrews West',
 'Saint Andrews East',
 'Queenwood (Hamilton City)',
 'St James',
 'Crawshaw',
 'Huntington',
 'Western Heights (Hamilton City)',
 'Nawton West',
 'Nawton East',
 'Chartwell',
 'Forest Lake (Hamilton City)',
 'Chedworth',
 'Beerescourt',
 'Miropiko',
 'Porritt',
 'Dinsdale North',
 'Dinsdale South',
 'Fairfield North (Hamilton City)',
 'Fairfield South (Hamilton City)',
 'Whitiora',
 'Enderley North',
 'Fairview Downs',
 'Temple View',
 'Swarbrick',
 'Kahikatea',
 'Frankton Junction',
 'Kirikiriroa',
 'Enderley South',
 'Greenhill Park',
 'Ruakura',
 'Claudelands',
 'Hamilton Central',
 'Hamilton Lake North',
 'Hamilton Lake South',
 'Peachgrove',
 'Hamilton East Village',
 'Hamilton West',
 'Greensboro',
 'Hamilton East Cook',
 'Melville North',
 'Hamilton East',
 'Melville South',
 'Deanwell',
 'Bader',
 'Hillcrest West (Hamilton City)',
 'Hillcrest East (Hamilton City)',
 'Silverdale (Hamilton City)',
 'Glenview',
 'Resthill',
 'Fitzroy (Hamilton City)',
 'Peacocke',
 'Te Pahu',
 'Ngahinapouri',
 'Lake Cameron',
 'Lake Ngaroto',
 'Kaipaki',
 'Pirongia',
 'Hautapu Rural',
 'Pokuru',
 'Te Rahu',
 'Fencourt',
 'Hautapu',
 'Cambridge North',
 'Cambridge West',
 'Cambridge East',
 'Cambridge Park-River Garden',
 'Oaklands-St Kilda',
 'Te Awamutu West',
 'Pukerimu',
 'Cambridge Central',
 'Te Awamutu North',
 'Leamington West',
 'Goodfellow Park',
 'Leamington South',
 'Tirau',
 'Leamington Central',
 'Leamington East',
 'Te Awamutu Stadium',
 'Te Awamutu Central',
 'Pekerau',
 'Fraser Street',
 'Sherwin Park',
 'St Leger',
 'Rotoorangi',
 'Tokanui',
 'Kihikihi Central',
 'Maungatautari',
 'Rotongata',
 'Pirongia Forest',
 'Honikiwi',
 'Te Kawa',
 'Otorohanga',
 'Maihiihi',
 'Puniu',
 'Putaruru Rural',
 'Putaruru',
 'Kinleith',
 'Paraonui',
 'Parkdale',
 'Matarawa',
 'Stanley Park',
 'Strathmore (South Waikato District)',
 'Tokoroa Central',
 'Moananui',
 'Herangi',
 'Hangatiki',
 'Aria',
 'Te Kuiti West',
 'Te Kuiti East',
 'Waipa Valley',
 'Tiroa',
 'Marotiri',
 'Mangakino',
 'Ohakuri',
 'Lake Taupo Bays',
 'Kinloch',
 'Wairakei-Broadlands',
 'Acacia Bay',
 'Brentwood (Taupo District)',
 'Nukuhau',
 'Rangatira Park',
 'Taupo Central West',
 'Tauhara',
 'Centennial',
 'Taupo Central East',
 'Mountview',
 'Bird Area',
 'Hilltop (Taupo District)',
 'Invergarry',
 'Waipahihi',
 'Richmond Heights',
 'Wharewaka',
 'Kaimanawa',
 'Waitahanui',
 'Turangi',
 ...]

In [5]:
def obtain_movement(df, mode, target):
    # Mode = Leaving from
    if mode:
        filtered = df[df["SA22023_V1_00_NAME_ASCII_usual_residence_address"] == target]
        return filtered
    # Mode = Coming to
    else:
        filtered = df[df["SA22023_V1_00_NAME_ASCII_workplace_address"] == target]
        return filtered

In [6]:
obtain_movement(df, 0, "Newmarket")

,SA22023_V1_00_usual_residence_address,SA22023_V1_00_NAME_usual_residence_address,SA22023_V1_00_NAME_ASCII_usual_residence_address,SA22023_V1_00_workplace_address,SA22023_V1_00_NAME_workplace_address,SA22023_V1_00_NAME_ASCII_workplace_address,2018_Work_at_home,2018_Drive_a_private_car_truck_or_van,2018_Drive_a_company_car_truck_or_van,2018_Passenger_in_a_car_truck_van_or_company_bus,...,2023_Drive_a_private_car_truck_or_van,2023_Drive_a_company_car_truck_or_van,2023_Passenger_in_a_car_truck_van_or_company_bus,2023_Public_bus,2023_Train,2023_Bicycle,2023_Walk_or_jog,2023_Ferry,2023_Other,2023_Total_stated
1628,110700,South Head,South Head,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
1741,111200,Puhoi Valley,Puhoi Valley,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
1773,111300,Warkworth East,Warkworth East,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1822,111601,Kaukapakapa,Kaukapakapa,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1853,111602,Kaukapakapa Rural,Kaukapakapa Rural,138501,Newmarket,Newmarket,0,6,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29760,166301,Bombay Hills,Bombay Hills,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29799,166400,Ararimu,Ararimu,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
30198,170001,Tuakau North,Tuakau North,138501,Newmarket,Newmarket,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
30354,170501,Pōkeno North,Pokeno North,138501,Newmarket,Newmarket,0,6,0,0,...,6,0,0,0,0,0,0,0,0,6
30401,170502,Pōkeno South,Pokeno South,138501,Newmarket,Newmarket,0,0,0,0,...,6,0,0,0,0,0,0,0,0,9

In [ ]:
path = r"data\statsnz-statistical-area-2-2023-generalised-SHP\statistical-area-2-2023-generalised.shp"
sa2shape2023 = gpd.read_file(path)
new_tiles = basemap_to_tiles(basemaps.CartoDB.Positron)

sa2shape2023 = sa2shape2023.to_crs(epsg=4326)
center_x = sa2shape2023.geometry.centroid.x.mean()
center_y = sa2shape2023.geometry.centroid.y.mean()
map = Map(center=(center_y, center_x), zoom=5, layers=(new_tiles, ))

geo_data = GeoData(geo_dataframe=sa2shape2023, style={'color': 'white', 'fillOpacity': 0.3, 'weight': 1},
    name='NZ Regions')

map.add_layer(geo_data)
display(map)

C:\Users\Jeff\AppData\Local\Temp\ipykernel_26556\1790880247.py:6: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  center_x = sa2shape2023.geometry.centroid.x.mean()
C:\Users\Jeff\AppData\Local\Temp\ipykernel_26556\1790880247.py:7: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  center_y = sa2shape2023.geometry.centroid.y.mean()

Map(center=[np.float64(-39.7324090852649), np.float64(173.89183241706436)], controls=(ZoomControl(options=['po…

In [11]:
map.add_layer(geo_data)