In [1]:
import pandas as pd
import geopandas as gpd

In [ ]:
df_2023 = gpd.read_file("data/statsnz-2023-census-main-means-of-travel-to-work-by-statistical-area-DBF/2023-census-main-means-of-travel-to-work-by-statistical-area.dbf")

df_2023

,SA22023_V1,SA22023__1,SA22023__2,SA22023__3,SA22023__4,SA22023__5,2018_Work_,2018_Drive,2018_Dri_1,2018_Passe,...,2023_Drive,2023_Dri_1,2023_Passe,2023_Publi,2023_Train,2023_Bicyc,2023_Walk_,2023_Ferry,2023_Other,2023_Total
0,100100,North Cape,North Cape,100100,North Cape,North Cape,144,117,33,9,...,165,39,12,-999,-999,-999,15,-999,6,438
1,100100,North Cape,North Cape,100200,Rangaunu Harbour,Rangaunu Harbour,-999,30,9,-999,...,42,6,-999,-999,-999,-999,-999,-999,-999,51
2,100100,North Cape,North Cape,100500,Tangonge,Tangonge,-999,-999,-999,-999,...,-999,6,-999,-999,-999,-999,-999,-999,-999,9
3,100100,North Cape,North Cape,100700,Kaitāia East,Kaitaia East,-999,51,15,-999,...,66,21,-999,-999,-999,-999,-999,-999,-999,93
4,100100,North Cape,North Cape,100800,Kaitāia West,Kaitaia West,-999,24,-999,-999,...,27,-999,-999,-999,-999,-999,-999,-999,-999,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65051,363301,Bluff,Bluff,362501,Strathern,Strathern,-999,-999,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,6
65052,363301,Bluff,Bluff,362601,Heidelberg,Heidelberg,-999,-999,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
65053,363301,Bluff,Bluff,363001,Clifton-Kew,Clifton-Kew,-999,9,-999,-999,...,21,-999,-999,-999,-999,-999,-999,-999,-999,21
65054,363301,Bluff,Bluff,363100,Woodend-Greenhills,Woodend-Greenhills,-999,33,-999,-999,...,27,-999,-999,-999,-999,-999,-999,-999,-999,30
65055,363301,Bluff,Bluff,363301,Bluff,Bluff,84,258,39,21,...,261,33,24,-999,-999,-999,30,-999,6,429

In [ ]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 65056 entries, 0 to 65055
Data columns (total 28 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SA22023_V1  65056 non-null  str
 1   SA22023__1  65056 non-null  str
 2   SA22023__2  65056 non-null  str
 3   SA22023__3  65056 non-null  str
 4   SA22023__4  65056 non-null  str
 5   SA22023__5  65056 non-null  str
 6   2018_Work_  65056 non-null  str
 7   2018_Drive  65056 non-null  str
 8   2018_Dri_1  65056 non-null  str
 9   2018_Passe  65056 non-null  str
 10  2018_Publi  65056 non-null  str
 11  2018_Train  65056 non-null  str
 12  2018_Bicyc  65056 non-null  str
 13  2018_Walk_  65056 non-null  str
 14  2018_Ferry  65056 non-null  str
 15  2018_Other  65056 non-null  str
 16  2018_Total  65056 non-null  str
 17  2023_Work_  65056 non-null  str
 18  2023_Drive  65056 non-null  str
 19  2023_Dri_1  65056 non-null  str
 20  2023_Passe  65056 non-null  str
 21  2023_Publi  65056 non-null  str
 22  2023_Train  65056 non-null  str
 23  2023_Bicyc  65056 non-null  str
 24  2023_Walk_  65056 non-null  str
 25  2023_Ferry  65056 non-null  str
 26  2023_Other  65056 non-null  str
 27  2023_Total  65056 non-null  str
dtypes: str(28)
memory usage: 13.9 MB

In [ ]:
df_2023.describe()

,SA22023_V1,SA22023__1,SA22023__2,SA22023__3,SA22023__4,SA22023__5,2018_Work_,2018_Drive,2018_Dri_1,2018_Passe,...,2023_Drive,2023_Dri_1,2023_Passe,2023_Publi,2023_Train,2023_Bicyc,2023_Walk_,2023_Ferry,2023_Other,2023_Total
count,65056,65056,65056,65056,65056,65056,65056,65056,65056,65056,...,65056,65056,65056,65056,65056,65056,65056,65056,65056,65056
unique,2280,2280,2280,2289,2289,2289,150,122,36,18,...,132,38,18,60,53,27,75,17,28,261
top,131100,Waterview,Waterview,145900,Penrose,Penrose,-999,-999,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,6
freq,85,85,85,623,623,623,62809,26321,57558,63168,...,22304,56888,62759,61973,64199,63482,61823,64914,64539,11806

In [ ]:
df_2018 = gpd.read_file("data/statsnz-2018-census-main-means-of-travel-to-work-by-statistical-area-DBF/2018-census-main-means-of-travel-to-work-by-statistical-area.dbf")